local:
  dialect: postgres
  datasource: host=localhost port=5433 user=postgres password=postgres dbname=ask sslmode=disable
  dir: migrations/schemas
  table: migrations

production:
  dialect: postgres
  datasource: host=$DB_HOST port=$DB_PORT user=$DB_USER password=$DB_PASS dbname=$DB_NAME sslmode=disable
  dir: migrations/schemas
  table: migrations
